// <auto-generated />
using Animenetcore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Animenetcore.Migrations
{
    [DbContext(typeof(AnimeContext))]
    [Migration("20180115200353_AddNewPropInAnimes")]
    partial class AddNewPropInAnimes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Animenetcore.Models.Anime", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("episodes");

                    b.Property<string>("name");

                    b.Property<int>("year");

                    b.HasKey("id");

                    b.ToTable("Animes");
                });
#pragma warning restore 612, 618
        }
    }
}
