// <auto-generated />
using Animenetcore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Animenetcore.Migrations
{
    [DbContext(typeof(AnimeContext))]
    [Migration("20180118185239_FixAnimeAndEpisodes")]
    partial class FixAnimeAndEpisodes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Animenetcore.Models.Anime", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.Property<int>("year");

                    b.HasKey("id");

                    b.ToTable("Animes");
                });

            modelBuilder.Entity("Animenetcore.Models.Episode", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("animeid");

                    b.Property<int>("episode");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.HasIndex("animeid");

                    b.ToTable("Episdes");
                });

            modelBuilder.Entity("Animenetcore.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("login");

                    b.Property<string>("name");

                    b.Property<string>("password");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Animenetcore.Models.Episode", b =>
                {
                    b.HasOne("Animenetcore.Models.Anime", "anime")
                        .WithMany("episodes")
                        .HasForeignKey("animeid");
                });
#pragma warning restore 612, 618
        }
    }
}
